import {Resource} from "i18next/typescript/options";

export const languages = [
    {label: "Português", value: "pt"},
    {label: "English", value: "en"},
];

export const languageResources: Resource = {
    en: {
        translation: {
            welcome: "Welcome",
            change_language: "Change Language",
            restore_default: "Restore Default",
            delete_db: "Delete Database",
            notice: "Notice",
            notice_content_1: "Hold the button to delete the database.\nThis action cannot be undone.",
            success: "Success",
            success_content_1: "Database deleted successfully.",
            select_language: "Select Language",
            settings: "Settings",
            calculate_price: "Calculate Price",
            ride_history: "Ride History",
            enter_origin_address: "Enter the origin address",
            origin_address: "Origin Address",
            enter_destination_address: "Enter the destination address",
            destination_address: "Destination Address",
            calculate: "Calculate",
            clear: "Clear",
            estimated_price: "Estimated Price",
            estimated_time: "Estimated Time",
            distance: "Distance",
            calculation_error: "Error calculating",
            not_selected: "Not selected",
            enter_address: "Enter the address",
            day_base_rate: "Day Base Rate",
            night_km_rate: "Price per Km at Night",
            day_km_rate: "Price per Km at Day",
            night_base_rate: "Night Base Rate",
            access_key: "Access Key",
            distance_meters: "Distance (meters)",
            time_seconds: "Time (seconds)",
            currency: "BRL",
            origin: "Origin",
            destination: "Destination",
            save: "Save",
            cancel: "Cancel",
            delete: "Delete",
            select_address: "Select an address",
            ride_history_header: "Ride History",
            distance_label: "Distance",
            time_label: "Time",
            price_label: "Price",
            note_label: "Note",
            date_label: "Date",
            new_ride: "New Ride",
            edit_ride: "Edit Ride",
            home: "Home",
            price_calculator: "Price Calculator",
            new_record_race: "New record",
            edit_record_race: "Edit record",
        },
    },
    pt: {
        translation: {
            welcome: "Bem-vindo",
            change_language: "Trocar Idioma",
            restore_default: "Restaurar Padrão",
            delete_db: "Deletar Banco de Dados",
            notice: "Aviso",
            notice_content_1: "Segure o botão para deletar o banco de dados.\nEsta ação não pode ser desfeita.",
            success: "Sucesso",
            success_content_1: "Banco de dados deletado com sucesso.",
            select_language: "Selecione o idioma",
            settings: "Configurações",
            calculate_price: "Calcular Preço",
            ride_history: "Histórico de Corridas",
            enter_origin_address: "Digite o endereço de origem",
            origin_address: "Endereço de Origem",
            enter_destination_address: "Digite o endereço de destino",
            destination_address: "Endereço de Destino",
            calculate: "Calcular",
            clear: "Limpar",
            estimated_price: "Preço Estimado",
            estimated_time: "Tempo Estimado",
            distance: "Distância",
            calculation_error: "Erro ao calcular",
            not_selected: "Não selecionado",
            enter_address: "Digite o endereço",
            day_base_rate: "Taxa base de Dia",
            night_km_rate: "Preço por Km de Noite",
            day_km_rate: "Preço por Km de Dia",
            night_base_rate: "Taxa base de Noite",
            access_key: "Chave de acesso",
            distance_meters: "Distância (metros)",
            time_seconds: "Tempo (segundos)",
            currency: "R$",
            origin: "Origem",
            destination: "Destino",
            save: "Salvar",
            cancel: "Cancelar",
            delete: "Deletar",
            select_address: "Selecione um endereço",
            ride_history_header: "Histórico de Corridas",
            distance_label: "Distância",
            time_label: "Tempo",
            price_label: "Preço",
            note_label: "Nota",
            date_label: "Data",
            new_ride: "Nova Corrida",
            edit_ride: "Editar Corrida",
            home: "Início",
            price_calculator: "Calculadora de Preço",
            new_record_race: "Novo registro de corrida",
            edit_record_race: "Editar registro de corrida",
        },
    },
};
